LIBRESPOT_NAME="Homie"
LIBRESPOT_BACKEND="pulseaudio"
LIBRESPOT_DEVICE_TYPE="speaker"
LIBRESPOT_BITRATE="320"
LIBRESPOT_EMIT_SINK_EVENTS=
LIBRESPOT_ONEVENT="/home/homie/projects/homie/run_raspotify_event_hook.sh"
LIBRESPOT_QUIET=
